//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace citasMedicasRest
{
  using Newtonsoft.Json;
  using System;
    using System.Collections.Generic;
  using System.Runtime.Serialization;

  public partial class cita
    {
        public int id { get; set; }
        public Nullable<int> medico { get; set; }
        public Nullable<int> paciente { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string estado { get; set; }
        public string detalles { get; set; }

    [JsonIgnore]
    [IgnoreDataMember]
    public virtual usuario usuario { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
    public virtual usuario usuario1 { get; set; }
    }
}
