//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace citasMedicasRest
{
  using Newtonsoft.Json;
  using System;
    using System.Collections.Generic;
  using System.Runtime.Serialization;

  public partial class usuario
    {
        public usuario()
        {
            this.citas = new HashSet<cita>();
            this.citas1 = new HashSet<cita>();
        }
    
        public int id { get; set; }
        public string identificacion { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string perfil { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string usuario1 { get; set; }
        public string password { get; set; }

    [JsonIgnore]
    [IgnoreDataMember]
    public virtual ICollection<cita> citas { get; set; }

    [JsonIgnore]
    [IgnoreDataMember]
    public virtual ICollection<cita> citas1 { get; set; }
    }
}
